### PR TITLE
Unit tests for WaitVisible method

### PR DESCRIPTION
**Pull request by nikulkarni**
Added unit tests for WaitVisible method. Also modified WaitVisible method a bit so that we have more control and unit tests can be written properly. And finally some formatting changes.

This will take care of https://github.com/paypal/nemo-view/issues/4

### CODE REVIEW

**Comment by nikulkarni** [comment]
While I was at it, I also took care of https://github.com/paypal/nemo-view/issues/6

**Comment by nikulkarni** [comment]
need to fix unit tests, will do

**Comment by nikulkarni** [comment]
fixed unit tests and all of them passed

**Comment by grawk** [comment]
Whoops looks like we've been working at cross purposes! I started working on 0.4 versions of nemo-view, nemo-drivex, and nemo-locatex.

Figuring it is the nemo-drivex.waitForElement method which should rightfully throw the error, I pushed the change down to that level and didn't make any changes to the nemo-view code:
https://github.com/grawk/nemo-view/compare/paypal:develop...grawk:0.4-develop?expand=1
https://github.com/grawk/nemo-drivex/compare/paypal:develop...0.4-develop?expand=1&w=1

Also figuring this for a breaking change, I thought it better to release a new minor version (yes it's not really meant for breaking changes but this is npm after all).

**Comment by grawk** [comment]
We need to decide if the error should be thrown in `nemo-drivex.waitForElement` or `nemo-view.*Wait*`

Can you think of any benefit of throwing in nemo-view vs nemo-drivex?

**Comment by grawk** [comment]
Also, any change needs to be merged to `develop` so closing this

**Comment by nikulkarni** [comment]
Ahh, I guess that's alright. I think its better throw exception from `nemo-drivex`. I'll remove those changes from this PR. Unit tests for `WaitVisible` are still valid and need to be merged. For some reason I didn't find develop branch when I submitted this PR, I see it now. I'll reopen the PR in a few.

**Pull request closed without merging**
