### PR TITLE
scroll browser window

### PR DESCRIPTION
**Pull request by gkushang**
Adding a method to scroll window by X, Y coordinates

### CODE REVIEW

**Comment by nikulkarni** [comment]
Any particular reason we need scroll? selenium-webdriver should by default scroll to an element and interact with it as a normal user would do. If it doesn't then its a bug in selenium-webdriver

**Comment by gkushang** [comment]
the reason I added this is because it will be useful for the app with Infinite scroll, e.g. [PayPal Deals](http://paypal.com/deals) loads more offers if user scrolls down.

**Comment by gkushang** [comment]
the build has failed. I will look at the failures

**Comment by nikulkarni** [comment]
Isn't there a see more button?
image

**Comment by gkushang** [comment]
yea, see more is on Offers tab but not other tabs. I can add the scrollDown method locally to my project if we think it won't be useful for others. I am okay with it.

**Comment by nikulkarni** [comment]
Yeah, I'm more inclined towards generic use cases. Also our core libraries should stay away from using JS executor. I would vote to add JS if we can fulfill a wider use case to bridge in gaps until selenium-webdriver adds such native support. 

I'll let @grawk decide :)

**Comment by gkushang** [comment]
sure. @grawk let me know. Also, the build has indentation-errors and so failing. I'll look further into it.

**Comment by nikulkarni** [comment]
@gkushang you can add jshint configuration to your project and reformat https://github.com/paypal/nemo-view/blob/master/.jshintrc

**Comment by grawk** [comment]
Thanks @gkushang for taking the time to work on this PR.

I wonder if it might be possible to do the same thing using `WebDriver.Window.setPosition(x, y)`.

Either way, I'd say nemo-view is not the place for this. nemo-view essentially abstracts the pain of locating and interacting with WebElements. Scrolling the window doesn't fit in with that.

I had though previously that, if there is a need, window related functionalities could be in another plugin (`nemo-window`?). For things like:
* scrolling
* switching between windows
* other?

I'm going to close this PR.

**Comment by gkushang** [comment]
Got it! Having another plugin sounds good because we will need window's related methods, e.g ```swtich window```, will work on it.

**Pull request closed without merging**
